# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encoder-widget2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DeenEncoderWidget(object):
    def setupUi(self, DeenEncoderWidget):
        DeenEncoderWidget.setObjectName("DeenEncoderWidget")
        DeenEncoderWidget.resize(1216, 893)
        self.gridLayout = QtWidgets.QGridLayout(DeenEncoderWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(DeenEncoderWidget)
        self.widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.side_menu = QtWidgets.QWidget(DeenEncoderWidget)
        self.side_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.decode_combo = QtWidgets.QComboBox(self.side_menu)
        self.decode_combo.setObjectName("decode_combo")
        self.decode_combo.addItem("")
        self.verticalLayout_3.addWidget(self.decode_combo)
        self.encode_combo = QtWidgets.QComboBox(self.side_menu)
        self.encode_combo.setObjectName("encode_combo")
        self.encode_combo.addItem("")
        self.verticalLayout_3.addWidget(self.encode_combo, 0, QtCore.Qt.AlignTop)
        self.uncompress_combo = QtWidgets.QComboBox(self.side_menu)
        self.uncompress_combo.setObjectName("uncompress_combo")
        self.uncompress_combo.addItem("")
        self.verticalLayout_3.addWidget(self.uncompress_combo)
        self.compress_combo = QtWidgets.QComboBox(self.side_menu)
        self.compress_combo.setObjectName("compress_combo")
        self.compress_combo.addItem("")
        self.verticalLayout_3.addWidget(self.compress_combo)
        self.disassemble_combo = QtWidgets.QComboBox(self.side_menu)
        self.disassemble_combo.setObjectName("disassemble_combo")
        self.disassemble_combo.addItem("")
        self.verticalLayout_3.addWidget(self.disassemble_combo)
        self.assemble_combo = QtWidgets.QComboBox(self.side_menu)
        self.assemble_combo.setObjectName("assemble_combo")
        self.assemble_combo.addItem("")
        self.verticalLayout_3.addWidget(self.assemble_combo)
        self.hash_combo = QtWidgets.QComboBox(self.side_menu)
        self.hash_combo.setObjectName("hash_combo")
        self.hash_combo.addItem("")
        self.verticalLayout_3.addWidget(self.hash_combo)
        self.misc_combo = QtWidgets.QComboBox(self.side_menu)
        self.misc_combo.setObjectName("misc_combo")
        self.misc_combo.addItem("")
        self.verticalLayout_3.addWidget(self.misc_combo)
        self.format_combo = QtWidgets.QComboBox(self.side_menu)
        self.format_combo.setObjectName("format_combo")
        self.format_combo.addItem("")
        self.verticalLayout_3.addWidget(self.format_combo)
        self.groupBox_2 = QtWidgets.QGroupBox(self.side_menu)
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 200))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toggle_text_view = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_text_view.setObjectName("toggle_text_view")
        self.verticalLayout_2.addWidget(self.toggle_text_view)
        self.toggle_hex_view = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_hex_view.setObjectName("toggle_hex_view")
        self.verticalLayout_2.addWidget(self.toggle_hex_view)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.side_menu)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_mode_label = QtWidgets.QLabel(self.groupBox)
        self.widget_mode_label.setObjectName("widget_mode_label")
        self.verticalLayout.addWidget(self.widget_mode_label)
        self.content_length_label = QtWidgets.QLabel(self.groupBox)
        self.content_length_label.setObjectName("content_length_label")
        self.verticalLayout.addWidget(self.content_length_label)
        self.current_plugin_label = QtWidgets.QLabel(self.groupBox)
        self.current_plugin_label.setObjectName("current_plugin_label")
        self.verticalLayout.addWidget(self.current_plugin_label)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.side_menu, 0, 1, 1, 1)
        self.content_area_layout_widget = QtWidgets.QWidget(DeenEncoderWidget)
        self.content_area_layout_widget.setObjectName("content_area_layout_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.content_area_layout_widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.content_area_layout = QtWidgets.QVBoxLayout()
        self.content_area_layout.setObjectName("content_area_layout")
        self.verticalLayout_5.addLayout(self.content_area_layout)
        self.gridLayout.addWidget(self.content_area_layout_widget, 0, 0, 4, 1)
        self.search_group = QtWidgets.QGroupBox(DeenEncoderWidget)
        self.search_group.setMaximumSize(QtCore.QSize(16777215, 115))
        self.search_group.setTitle("")
        self.search_group.setObjectName("search_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.search_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_progress_bar = QtWidgets.QProgressBar(self.search_group)
        self.search_progress_bar.setProperty("value", 24)
        self.search_progress_bar.setObjectName("search_progress_bar")
        self.gridLayout_2.addWidget(self.search_progress_bar, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.search_group)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.search_area = QtWidgets.QLineEdit(self.search_group)
        self.search_area.setObjectName("search_area")
        self.horizontalLayout_3.addWidget(self.search_area)
        self.search_button = QtWidgets.QPushButton(self.search_group)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_3.addWidget(self.search_button)
        self.search_clear_button = QtWidgets.QPushButton(self.search_group)
        self.search_clear_button.setObjectName("search_clear_button")
        self.horizontalLayout_3.addWidget(self.search_clear_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.search_matches_label = QtWidgets.QLabel(self.search_group)
        self.search_matches_label.setObjectName("search_matches_label")
        self.gridLayout_2.addWidget(self.search_matches_label, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.search_group, 5, 0, 1, 1)
        self.error_message_layout_widget = QtWidgets.QWidget(DeenEncoderWidget)
        self.error_message_layout_widget.setObjectName("error_message_layout_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.error_message_layout_widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.error_message_layout = QtWidgets.QVBoxLayout()
        self.error_message_layout.setObjectName("error_message_layout")
        self.verticalLayout_8.addLayout(self.error_message_layout)
        self.gridLayout.addWidget(self.error_message_layout_widget, 7, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(DeenEncoderWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.clear_button = QtWidgets.QPushButton(self.widget_2)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_3.addWidget(self.clear_button, 0, 0, 1, 1)
        self.move_to_root_button = QtWidgets.QPushButton(self.widget_2)
        self.move_to_root_button.setObjectName("move_to_root_button")
        self.gridLayout_3.addWidget(self.move_to_root_button, 0, 1, 1, 1)
        self.hide_side_menu = QtWidgets.QPushButton(self.widget_2)
        self.hide_side_menu.setObjectName("hide_side_menu")
        self.gridLayout_3.addWidget(self.hide_side_menu, 0, 5, 1, 1)
        self.copy_to_clipboard_button = QtWidgets.QPushButton(self.widget_2)
        self.copy_to_clipboard_button.setObjectName("copy_to_clipboard_button")
        self.gridLayout_3.addWidget(self.copy_to_clipboard_button, 0, 2, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.widget_2)
        self.save_button.setObjectName("save_button")
        self.gridLayout_3.addWidget(self.save_button, 0, 3, 1, 1)
        self.hide_search_box = QtWidgets.QPushButton(self.widget_2)
        self.hide_search_box.setObjectName("hide_search_box")
        self.gridLayout_3.addWidget(self.hide_search_box, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 4, 0, 1, 1)

        self.retranslateUi(DeenEncoderWidget)
        QtCore.QMetaObject.connectSlotsByName(DeenEncoderWidget)

    def retranslateUi(self, DeenEncoderWidget):
        _translate = QtCore.QCoreApplication.translate
        DeenEncoderWidget.setWindowTitle(_translate("DeenEncoderWidget", "Form"))
        self.decode_combo.setItemText(0, _translate("DeenEncoderWidget", "Decode"))
        self.encode_combo.setItemText(0, _translate("DeenEncoderWidget", "Encode"))
        self.uncompress_combo.setItemText(0, _translate("DeenEncoderWidget", "Uncompress"))
        self.compress_combo.setItemText(0, _translate("DeenEncoderWidget", "Compress"))
        self.disassemble_combo.setItemText(0, _translate("DeenEncoderWidget", "Disassemble"))
        self.assemble_combo.setItemText(0, _translate("DeenEncoderWidget", "Assemble"))
        self.hash_combo.setItemText(0, _translate("DeenEncoderWidget", "Hash"))
        self.misc_combo.setItemText(0, _translate("DeenEncoderWidget", "Miscellaneous"))
        self.format_combo.setItemText(0, _translate("DeenEncoderWidget", "Format"))
        self.toggle_text_view.setText(_translate("DeenEncoderWidget", "Te&xt view"))
        self.toggle_hex_view.setText(_translate("DeenEncoderWidget", "He&x view"))
        self.widget_mode_label.setText(_translate("DeenEncoderWidget", "Mode:"))
        self.content_length_label.setText(_translate("DeenEncoderWidget", "Length:"))
        self.current_plugin_label.setText(_translate("DeenEncoderWidget", "Plugin:"))
        self.label_2.setText(_translate("DeenEncoderWidget", "Search:"))
        self.search_button.setText(_translate("DeenEncoderWidget", "Search"))
        self.search_clear_button.setText(_translate("DeenEncoderWidget", "Clear"))
        self.search_matches_label.setText(_translate("DeenEncoderWidget", "Matches: 0"))
        self.clear_button.setToolTip(_translate("DeenEncoderWidget", "Clear widget content"))
        self.clear_button.setText(_translate("DeenEncoderWidget", "Clear"))
        self.move_to_root_button.setToolTip(_translate("DeenEncoderWidget", "Move content to root widget"))
        self.move_to_root_button.setText(_translate("DeenEncoderWidget", "Move"))
        self.hide_side_menu.setText(_translate("DeenEncoderWidget", "Sidebar"))
        self.copy_to_clipboard_button.setToolTip(_translate("DeenEncoderWidget", "Copy content to clipboard"))
        self.copy_to_clipboard_button.setText(_translate("DeenEncoderWidget", "Clipboard"))
        self.save_button.setToolTip(_translate("DeenEncoderWidget", "Save content to file"))
        self.save_button.setText(_translate("DeenEncoderWidget", "Save"))
        self.hide_search_box.setText(_translate("DeenEncoderWidget", "Search"))

