# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encoder-widget2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DeenEncoderWidget(object):
    def setupUi(self, DeenEncoderWidget):
        DeenEncoderWidget.setObjectName("DeenEncoderWidget")
        DeenEncoderWidget.resize(1009, 699)
        self.gridLayout = QtWidgets.QGridLayout(DeenEncoderWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtWidgets.QFrame(DeenEncoderWidget)
        self.line_3.setBaseSize(QtCore.QSize(0, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 3)
        self.content_area_layout = QtWidgets.QVBoxLayout()
        self.content_area_layout.setObjectName("content_area_layout")
        self.gridLayout.addLayout(self.content_area_layout, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clear_button = QtWidgets.QPushButton(DeenEncoderWidget)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.move_to_root_button = QtWidgets.QPushButton(DeenEncoderWidget)
        self.move_to_root_button.setObjectName("move_to_root_button")
        self.horizontalLayout_2.addWidget(self.move_to_root_button)
        self.copy_to_clipboard_button = QtWidgets.QPushButton(DeenEncoderWidget)
        self.copy_to_clipboard_button.setObjectName("copy_to_clipboard_button")
        self.horizontalLayout_2.addWidget(self.copy_to_clipboard_button)
        self.save_button = QtWidgets.QPushButton(DeenEncoderWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(DeenEncoderWidget)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.search_area = QtWidgets.QLineEdit(self.groupBox_4)
        self.search_area.setObjectName("search_area")
        self.horizontalLayout_3.addWidget(self.search_area)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.search_matches_label = QtWidgets.QLabel(self.groupBox_4)
        self.search_matches_label.setObjectName("search_matches_label")
        self.gridLayout_2.addWidget(self.search_matches_label, 0, 2, 1, 1)
        self.search_progress_bar = QtWidgets.QProgressBar(self.groupBox_4)
        self.search_progress_bar.setProperty("value", 24)
        self.search_progress_bar.setObjectName("search_progress_bar")
        self.gridLayout_2.addWidget(self.search_progress_bar, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 3, 0, 1, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.compress_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.compress_combo.setObjectName("compress_combo")
        self.compress_combo.addItem("")
        self.gridLayout_4.addWidget(self.compress_combo, 4, 0, 1, 1)
        self.hash_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.hash_combo.setObjectName("hash_combo")
        self.hash_combo.addItem("")
        self.gridLayout_4.addWidget(self.hash_combo, 5, 0, 1, 1)
        self.format_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.format_combo.setObjectName("format_combo")
        self.format_combo.addItem("")
        self.gridLayout_4.addWidget(self.format_combo, 7, 0, 1, 1)
        self.uncompress_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.uncompress_combo.setObjectName("uncompress_combo")
        self.uncompress_combo.addItem("")
        self.gridLayout_4.addWidget(self.uncompress_combo, 3, 0, 1, 1)
        self.encode_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.encode_combo.setObjectName("encode_combo")
        self.encode_combo.addItem("")
        self.gridLayout_4.addWidget(self.encode_combo, 2, 0, 1, 1)
        self.misc_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.misc_combo.setObjectName("misc_combo")
        self.misc_combo.addItem("")
        self.gridLayout_4.addWidget(self.misc_combo, 6, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(DeenEncoderWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_mode_label = QtWidgets.QLabel(self.groupBox)
        self.widget_mode_label.setObjectName("widget_mode_label")
        self.verticalLayout.addWidget(self.widget_mode_label)
        self.content_length_label = QtWidgets.QLabel(self.groupBox)
        self.content_length_label.setObjectName("content_length_label")
        self.verticalLayout.addWidget(self.content_length_label)
        self.current_plugin_label = QtWidgets.QLabel(self.groupBox)
        self.current_plugin_label.setObjectName("current_plugin_label")
        self.verticalLayout.addWidget(self.current_plugin_label)
        self.gridLayout_4.addWidget(self.groupBox, 9, 0, 1, 1, QtCore.Qt.AlignTop)
        self.groupBox_2 = QtWidgets.QGroupBox(DeenEncoderWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toggle_text_view = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_text_view.setObjectName("toggle_text_view")
        self.verticalLayout_2.addWidget(self.toggle_text_view)
        self.toggle_hex_view = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_hex_view.setObjectName("toggle_hex_view")
        self.verticalLayout_2.addWidget(self.toggle_hex_view)
        self.gridLayout_4.addWidget(self.groupBox_2, 8, 0, 1, 1, QtCore.Qt.AlignTop)
        self.decode_combo = QtWidgets.QComboBox(DeenEncoderWidget)
        self.decode_combo.setObjectName("decode_combo")
        self.decode_combo.addItem("")
        self.gridLayout_4.addWidget(self.decode_combo, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 2, 1, 1)
        self.error_message_layout = QtWidgets.QHBoxLayout()
        self.error_message_layout.setObjectName("error_message_layout")
        self.gridLayout.addLayout(self.error_message_layout, 2, 0, 1, 3)

        self.retranslateUi(DeenEncoderWidget)
        QtCore.QMetaObject.connectSlotsByName(DeenEncoderWidget)

    def retranslateUi(self, DeenEncoderWidget):
        _translate = QtCore.QCoreApplication.translate
        DeenEncoderWidget.setWindowTitle(_translate("DeenEncoderWidget", "Form"))
        self.clear_button.setToolTip(_translate("DeenEncoderWidget", "Clear widget content"))
        self.clear_button.setText(_translate("DeenEncoderWidget", "Clear"))
        self.move_to_root_button.setToolTip(_translate("DeenEncoderWidget", "Move content to root widget"))
        self.move_to_root_button.setText(_translate("DeenEncoderWidget", "Move"))
        self.copy_to_clipboard_button.setToolTip(_translate("DeenEncoderWidget", "Copy content to clipboard"))
        self.copy_to_clipboard_button.setText(_translate("DeenEncoderWidget", "Clipboard"))
        self.save_button.setToolTip(_translate("DeenEncoderWidget", "Save content to file"))
        self.save_button.setText(_translate("DeenEncoderWidget", "Save"))
        self.label_2.setText(_translate("DeenEncoderWidget", "Search:"))
        self.search_matches_label.setText(_translate("DeenEncoderWidget", "Matches: 0"))
        self.compress_combo.setItemText(0, _translate("DeenEncoderWidget", "Compress"))
        self.hash_combo.setItemText(0, _translate("DeenEncoderWidget", "Hash"))
        self.format_combo.setItemText(0, _translate("DeenEncoderWidget", "Format"))
        self.uncompress_combo.setItemText(0, _translate("DeenEncoderWidget", "Uncompress"))
        self.encode_combo.setItemText(0, _translate("DeenEncoderWidget", "Encode"))
        self.misc_combo.setItemText(0, _translate("DeenEncoderWidget", "Miscellaneous"))
        self.widget_mode_label.setText(_translate("DeenEncoderWidget", "Mode:"))
        self.content_length_label.setText(_translate("DeenEncoderWidget", "Length:"))
        self.current_plugin_label.setText(_translate("DeenEncoderWidget", "Plugin:"))
        self.toggle_text_view.setText(_translate("DeenEncoderWidget", "Te&xt view"))
        self.toggle_hex_view.setText(_translate("DeenEncoderWidget", "He&x view"))
        self.decode_combo.setItemText(0, _translate("DeenEncoderWidget", "Decode"))

